### ISSUE TITLE
How do I debug "error=Grant: missing session or misconfigured provider"

### ISSUE THREAD

**Issue by Eruant** [simov/grant#63] opened 2016-09-06 11:47 UTC
I've used grant for a while, and have got it working for my app. However occasionally I get the following error:
`error=Grant%3A%20missing%20session%20or%20misconfigured%20provider`

It's not clear what is causing the issue. Is there a way of getting a better output?

**Comment by simov** [comment] 2016-09-06 11:52
This generic error message was introduced here https://github.com/simov/grant/pull/23 Is it possible that you are experiencing it in similar circumstances?

**Comment by Eruant** [comment] 2016-09-06 12:02
I start at:
`get /connect/musicqubed {} 302` which redirects me to OAuth2 server.

I then get redirected back to:
`get /connect/musicqubed/callback {"code":"<code>","state":"<state>"} 200`

When looking at the `grant` variable it is set to `{}`. It looks as if the session never got set.

**Comment by simov** [comment] 2016-09-06 14:06
Missing session can definitely result in that error. Which framework+version do you use, Express, Koa, Hapi?

Take a look at these tests: https://github.com/simov/grant/blob/master/test/consumer/express/error.js#L180-L243 

If the bare minimum configuration is missing in either the connect or the callback routes in Grant, then Grant simply tells you that either your configuration is incorrect, or your session data is missing for some reason.

Either way Grant is not trying to fix your errors, if you provide me with a code example sufficient enough to reproduce the bug, I would probably be able to help you.

**Comment by Eruant** [comment] 2016-09-06 14:37
I'm using Hapi.

I've investigated this further, and it seems that all cookies stored by yar get wiped upon return from the my OAuth2 provider. It looks like this issue is either coming from yar or my provider.

This issue can be closed for now. It seems most likely that the issue isn't being caused here.

**Comment by simov** [comment] 2016-09-06 14:42
Can you give me the *exact* version of Hapi and Yar that you are using? That way I can at least run the test suite against them. Currently the Hapi version used for testing is pinned to an older version due to compatibility issues with older versions of Node.

**Comment by Eruant** [comment] 2016-09-06 15:03
Sure, here you go

| Package | Version |
|---|---|
| hapi | 15.03 |
| yar | 7.0.2 |
| grant-hapi | 3.6.4 |

**Comment by simov** [comment] 2016-09-06 16:11
Tests seems to be passing on my end. I'm closing this issue for now, feel free to re-open it and/or add something to it.

**Closed by simov** 2016-09-06 16:11 UTC

**Comment by Eruant** [comment] 2016-09-06 16:15
I've had some success with Safari, but not Chrome or Firefox. It could possibly be related to the way the cookies and sessions are set. If I figure this out I'll add the solution in case anyone else has the same issue in the future.

**Comment by simov** [comment] 2016-09-06 16:18
That would be great! :+1:

**Comment by Eruant** [comment] 2016-09-07 09:12
The issue appears to be with yar, and so I've opened a new ticket:
https://github.com/hapijs/yar/issues/101
